# Generated by Django 4.2.5 on 2023-09-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')], default=(3, 'Others'), max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
